apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  # defines which pods are going to be represented by this Service
  # service becomes a network endpoint by either services or maybe external users to connect to (eg browser)
  selector:
    app: webapp
    release: "0-5"

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort
